# Using latest API version
version: '3.8'

services:
  weather-web:
    build:
       dockerfile: ./Dockerfile
       context: ./
       network: host
    container_name: weather-web
    image: weather-web:latest
    restart: always
    ports:
      - "3030:80"

  # weather-graphql:
  #   container_name: weather-graphql
  #   image: weather-graphql:main-22-c75ad07
  #   restart: always
  #   ports:
  #     - "4040:4000"

    