apiVersion: v1
kind: Service
metadata:
  name: weather-app
  namespace: nodejs
  labels:
    app: nodejs
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
  selector:
    app: weather-app